[12:04:14,228] [main]  WARN (NativeCodeLoader.java:62) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[12:04:14,329] [main]  INFO (RecoverableZooKeeper.java:121) - Process identifier=hconnection-0x4ab2945d connecting to ZooKeeper ensemble=localhost:2181
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:host.name=localhost
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.version=1.7.0_60
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.vendor=Oracle Corporation
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.home=/usr/java/jdk1.7.0_60/jre
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.class.path=/home/kylin/project/data/hbase-quickstart/target/classes:/home/kylin/.m2/repository/org/apache/hbase/hbase-client/0.98.8-hadoop2/hbase-client-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-annotations/0.98.8-hadoop2/hbase-annotations-0.98.8-hadoop2.jar:/usr/java/jdk1.7.0_60/lib/tools.jar:/home/kylin/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-common/0.98.8-hadoop2/hbase-common-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-protocol/0.98.8-hadoop2/hbase-protocol-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/commons-codec/commons-codec/1.7/commons-codec-1.7.jar:/home/kylin/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/kylin/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/kylin/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/home/kylin/.m2/repository/com/google/guava/guava/12.0.1/guava-12.0.1.jar:/home/kylin/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/home/kylin/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/home/kylin/.m2/repository/io/netty/netty/3.6.6.Final/netty-3.6.6.Final.jar:/home/kylin/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/home/kylin/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar:/home/kylin/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar:/home/kylin/.m2/repository/org/cloudera/htrace/htrace-core/2.04/htrace-core-2.04.jar:/home/kylin/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.8.8/jackson-mapper-asl-1.8.8.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar:/home/kylin/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar:/home/kylin/.m2/repository/org/jruby/jcodings/jcodings/1.0.8/jcodings-1.0.8.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-common/2.2.0/hadoop-common-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-annotations/2.2.0/hadoop-annotations-2.2.0.jar:/home/kylin/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/home/kylin/.m2/repository/org/apache/commons/commons-math/2.1/commons-math-2.1.jar:/home/kylin/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar:/home/kylin/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/home/kylin/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:/home/kylin/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar:/home/kylin/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar:/home/kylin/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/home/kylin/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar:/home/kylin/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar:/home/kylin/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.8.3/jackson-jaxrs-1.8.3.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-xc/1.8.3/jackson-xc-1.8.3.jar:/home/kylin/.m2/repository/commons-el/commons-el/1.0/commons-el-1.0.jar:/home/kylin/.m2/repository/net/java/dev/jets3t/jets3t/0.6.1/jets3t-0.6.1.jar:/home/kylin/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/home/kylin/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/home/kylin/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar:/home/kylin/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/home/kylin/.m2/repository/org/apache/avro/avro/1.7.4/avro-1.7.4.jar:/home/kylin/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar:/home/kylin/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar:/home/kylin/.m2/repository/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar:/home/kylin/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:/home/kylin/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-auth/2.2.0/hadoop-auth-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/2.2.0/hadoop-mapreduce-client-core-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.2.0/hadoop-yarn-common-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.2.0/hadoop-yarn-api-2.2.0.jar:/home/kylin/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar:/home/kylin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/kylin/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar:/home/kylin/.m2/repository/asm/asm/3.1/asm-3.1.jar:/home/kylin/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar:/home/kylin/.m2/repository/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar:/home/kylin/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.io.tmpdir=/tmp
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.compiler=<NA>
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.name=Linux
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.arch=amd64
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.version=2.6.32-431.20.3.el6.x86_64
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:user.name=kylin
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:user.home=/home/kylin
[12:04:14,342] [main]  INFO (Environment.java:100) - Client environment:user.dir=/home/kylin/project/data/hbase-quickstart
[12:04:14,343] [main]  INFO (ZooKeeper.java:438) - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x4ab2945d, quorum=localhost:2181, baseZNode=/hbase
[12:04:14,363] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:975) - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[12:04:14,369] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:852) - Socket connection established to localhost/127.0.0.1:2181, initiating session
[12:04:14,450] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:1235) - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14a08a8e944000b, negotiated timeout = 40000
[12:05:23,178] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=10, retries=35, retryTime=68519ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:05:43,217] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=11, retries=35, retryTime=88561ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:03,297] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=12, retries=35, retryTime=108641ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:23,400] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=13, retries=35, retryTime=128744ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:43,486] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=14, retries=35, retryTime=148830ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:03,655] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=15, retries=35, retryTime=168999ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:23,760] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=16, retries=35, retryTime=189104ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:43,955] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=17, retries=35, retryTime=209298ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:04,054] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=18, retries=35, retryTime=229398ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:24,094] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=19, retries=35, retryTime=249438ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:44,166] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=20, retries=35, retryTime=269510ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:04,263] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=21, retries=35, retryTime=289607ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:24,365] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=22, retries=35, retryTime=309709ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:44,476] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=23, retries=35, retryTime=329820ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:04,584] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=24, retries=35, retryTime=349928ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:24,749] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=25, retries=35, retryTime=370093ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:44,897] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=26, retries=35, retryTime=390241ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:04,975] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=27, retries=35, retryTime=410319ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:25,170] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=28, retries=35, retryTime=430514ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:45,360] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=29, retries=35, retryTime=450704ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:05,379] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=30, retries=35, retryTime=470723ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:25,525] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=31, retries=35, retryTime=490869ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:45,544] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=32, retries=35, retryTime=510888ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:13:05,596] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=33, retries=35, retryTime=530940ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:13:25,614] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=34, retries=35, retryTime=550958ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
Exception in thread "main" org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=35, exceptions:
Tue Dec 02 12:04:14 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:15 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:15 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:16 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:18 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:22 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:32 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:42 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:52 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:45 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:05 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:45 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:13:05 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:13:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:133)
	at org.apache.hadoop.hbase.client.HTable.getRowOrBefore(HTable.java:721)
	at org.apache.hadoop.hbase.examples.ConnectionRefuseReproduce.main(ConnectionRefuseReproduce.java:37)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:493)
	at org.apache.hadoop.hbase.ipc.RpcClient$Connection.setupConnection(RpcClient.java:578)
	at org.apache.hadoop.hbase.ipc.RpcClient$Connection.setupIOstreams(RpcClient.java:868)
	at org.apache.hadoop.hbase.ipc.RpcClient.getConnection(RpcClient.java:1543)
	at org.apache.hadoop.hbase.ipc.RpcClient.call(RpcClient.java:1442)
	at org.apache.hadoop.hbase.ipc.RpcClient.callBlockingMethod(RpcClient.java:1661)
	at org.apache.hadoop.hbase.ipc.RpcClient$BlockingRpcChannelImplementation.callBlockingMethod(RpcClient.java:1719)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:30363)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.getRowOrBefore(ProtobufUtil.java:1546)
	at org.apache.hadoop.hbase.client.HTable$2.call(HTable.java:717)
	at org.apache.hadoop.hbase.client.HTable$2.call(HTable.java:715)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:117)
	... 2 more
[12:04:14,228] [main]  WARN (NativeCodeLoader.java:62) - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[12:04:14,329] [main]  INFO (RecoverableZooKeeper.java:121) - Process identifier=hconnection-0x4ab2945d connecting to ZooKeeper ensemble=localhost:2181
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:host.name=localhost
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.version=1.7.0_60
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.vendor=Oracle Corporation
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.home=/usr/java/jdk1.7.0_60/jre
[12:04:14,339] [main]  INFO (Environment.java:100) - Client environment:java.class.path=/home/kylin/project/data/hbase-quickstart/target/classes:/home/kylin/.m2/repository/org/apache/hbase/hbase-client/0.98.8-hadoop2/hbase-client-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-annotations/0.98.8-hadoop2/hbase-annotations-0.98.8-hadoop2.jar:/usr/java/jdk1.7.0_60/lib/tools.jar:/home/kylin/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-common/0.98.8-hadoop2/hbase-common-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/kylin/.m2/repository/org/apache/hbase/hbase-protocol/0.98.8-hadoop2/hbase-protocol-0.98.8-hadoop2.jar:/home/kylin/.m2/repository/commons-codec/commons-codec/1.7/commons-codec-1.7.jar:/home/kylin/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar:/home/kylin/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar:/home/kylin/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/home/kylin/.m2/repository/com/google/guava/guava/12.0.1/guava-12.0.1.jar:/home/kylin/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar:/home/kylin/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar:/home/kylin/.m2/repository/io/netty/netty/3.6.6.Final/netty-3.6.6.Final.jar:/home/kylin/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar:/home/kylin/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar:/home/kylin/.m2/repository/org/slf4j/slf4j-log4j12/1.6.1/slf4j-log4j12-1.6.1.jar:/home/kylin/.m2/repository/org/cloudera/htrace/htrace-core/2.04/htrace-core-2.04.jar:/home/kylin/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.8.8/jackson-mapper-asl-1.8.8.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.8.8/jackson-core-asl-1.8.8.jar:/home/kylin/.m2/repository/org/jruby/joni/joni/2.1.2/joni-2.1.2.jar:/home/kylin/.m2/repository/org/jruby/jcodings/jcodings/1.0.8/jcodings-1.0.8.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-common/2.2.0/hadoop-common-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-annotations/2.2.0/hadoop-annotations-2.2.0.jar:/home/kylin/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar:/home/kylin/.m2/repository/org/apache/commons/commons-math/2.1/commons-math-2.1.jar:/home/kylin/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar:/home/kylin/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar:/home/kylin/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar:/home/kylin/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-json/1.9/jersey-json-1.9.jar:/home/kylin/.m2/repository/org/codehaus/jettison/jettison/1.1/jettison-1.1.jar:/home/kylin/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar:/home/kylin/.m2/repository/com/sun/xml/bind/jaxb-impl/2.2.3-1/jaxb-impl-2.2.3-1.jar:/home/kylin/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar:/home/kylin/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.8.3/jackson-jaxrs-1.8.3.jar:/home/kylin/.m2/repository/org/codehaus/jackson/jackson-xc/1.8.3/jackson-xc-1.8.3.jar:/home/kylin/.m2/repository/commons-el/commons-el/1.0/commons-el-1.0.jar:/home/kylin/.m2/repository/net/java/dev/jets3t/jets3t/0.6.1/jets3t-0.6.1.jar:/home/kylin/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar:/home/kylin/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar:/home/kylin/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar:/home/kylin/.m2/repository/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar:/home/kylin/.m2/repository/org/apache/avro/avro/1.7.4/avro-1.7.4.jar:/home/kylin/.m2/repository/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar:/home/kylin/.m2/repository/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar:/home/kylin/.m2/repository/com/jcraft/jsch/0.1.42/jsch-0.1.42.jar:/home/kylin/.m2/repository/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar:/home/kylin/.m2/repository/org/tukaani/xz/1.0/xz-1.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-auth/2.2.0/hadoop-auth-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/2.2.0/hadoop-mapreduce-client-core-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.2.0/hadoop-yarn-common-2.2.0.jar:/home/kylin/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.2.0/hadoop-yarn-api-2.2.0.jar:/home/kylin/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar:/home/kylin/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/kylin/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/home/kylin/.m2/repository/com/sun/jersey/jersey-server/1.9/jersey-server-1.9.jar:/home/kylin/.m2/repository/asm/asm/3.1/asm-3.1.jar:/home/kylin/.m2/repository/com/sun/jersey/contribs/jersey-guice/1.9/jersey-guice-1.9.jar:/home/kylin/.m2/repository/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar:/home/kylin/.m2/repository/com/github/stephenc/findbugs/findbugs-annotations/1.3.9-1/findbugs-annotations-1.3.9-1.jar
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.io.tmpdir=/tmp
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:java.compiler=<NA>
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.name=Linux
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.arch=amd64
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:os.version=2.6.32-431.20.3.el6.x86_64
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:user.name=kylin
[12:04:14,340] [main]  INFO (Environment.java:100) - Client environment:user.home=/home/kylin
[12:04:14,342] [main]  INFO (Environment.java:100) - Client environment:user.dir=/home/kylin/project/data/hbase-quickstart
[12:04:14,343] [main]  INFO (ZooKeeper.java:438) - Initiating client connection, connectString=localhost:2181 sessionTimeout=90000 watcher=hconnection-0x4ab2945d, quorum=localhost:2181, baseZNode=/hbase
[12:04:14,363] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:975) - Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error)
[12:04:14,369] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:852) - Socket connection established to localhost/127.0.0.1:2181, initiating session
[12:04:14,450] [main-SendThread(localhost:2181)]  INFO (ClientCnxn.java:1235) - Session establishment complete on server localhost/127.0.0.1:2181, sessionid = 0x14a08a8e944000b, negotiated timeout = 40000
[12:05:23,178] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=10, retries=35, retryTime=68519ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:05:43,217] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=11, retries=35, retryTime=88561ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:03,297] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=12, retries=35, retryTime=108641ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:23,400] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=13, retries=35, retryTime=128744ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:06:43,486] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=14, retries=35, retryTime=148830ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:03,655] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=15, retries=35, retryTime=168999ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:23,760] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=16, retries=35, retryTime=189104ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:07:43,955] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=17, retries=35, retryTime=209298ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:04,054] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=18, retries=35, retryTime=229398ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:24,094] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=19, retries=35, retryTime=249438ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:08:44,166] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=20, retries=35, retryTime=269510ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:04,263] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=21, retries=35, retryTime=289607ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:24,365] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=22, retries=35, retryTime=309709ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:09:44,476] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=23, retries=35, retryTime=329820ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:04,584] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=24, retries=35, retryTime=349928ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:24,749] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=25, retries=35, retryTime=370093ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:10:44,897] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=26, retries=35, retryTime=390241ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:04,975] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=27, retries=35, retryTime=410319ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:25,170] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=28, retries=35, retryTime=430514ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:11:45,360] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=29, retries=35, retryTime=450704ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:05,379] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=30, retries=35, retryTime=470723ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:25,525] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=31, retries=35, retryTime=490869ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:12:45,544] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=32, retries=35, retryTime=510888ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:13:05,596] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=33, retries=35, retryTime=530940ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
[12:13:25,614] [main]  INFO (RpcRetryingCaller.java:120) - Call exception, tries=34, retries=35, retryTime=550958ms, msg=row 'Customer,101,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,38776,1417484497885, seqNum=0
Exception in thread "main" org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=35, exceptions:
Tue Dec 02 12:04:14 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:15 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:15 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:16 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, org.apache.hadoop.hbase.ipc.RpcClient$FailedServerException: This server is in the failed servers list: localhost/127.0.0.1:38776
Tue Dec 02 12:04:18 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:22 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:32 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:42 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:04:52 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:05:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:06:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:03 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:23 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:07:43 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:08:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:09:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:24 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:10:44 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:04 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:11:45 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:05 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:12:45 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:13:05 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused
Tue Dec 02 12:13:25 CST 2014, org.apache.hadoop.hbase.client.RpcRetryingCaller@50b5c214, java.net.ConnectException: Connection refused

	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:133)
	at org.apache.hadoop.hbase.client.HTable.getRowOrBefore(HTable.java:721)
	at org.apache.hadoop.hbase.examples.ConnectionRefuseReproduce.main(ConnectionRefuseReproduce.java:37)
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:739)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:529)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:493)
	at org.apache.hadoop.hbase.ipc.RpcClient$Connection.setupConnection(RpcClient.java:578)
	at org.apache.hadoop.hbase.ipc.RpcClient$Connection.setupIOstreams(RpcClient.java:868)
	at org.apache.hadoop.hbase.ipc.RpcClient.getConnection(RpcClient.java:1543)
	at org.apache.hadoop.hbase.ipc.RpcClient.call(RpcClient.java:1442)
	at org.apache.hadoop.hbase.ipc.RpcClient.callBlockingMethod(RpcClient.java:1661)
	at org.apache.hadoop.hbase.ipc.RpcClient$BlockingRpcChannelImplementation.callBlockingMethod(RpcClient.java:1719)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.get(ClientProtos.java:30363)
	at org.apache.hadoop.hbase.protobuf.ProtobufUtil.getRowOrBefore(ProtobufUtil.java:1546)
	at org.apache.hadoop.hbase.client.HTable$2.call(HTable.java:717)
	at org.apache.hadoop.hbase.client.HTable$2.call(HTable.java:715)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:117)
	... 2 more

